version: '2'
services:
    lawchange-app:
        image: lawchange
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://lawchange-postgresql:5432/lawchange
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lawchange-postgresql:
        extends:
            file: postgresql.yml
            service: lawchange-postgresql
